### ISSUE TITLE
Filter by Native Environment Doesn't Work

### ISSUE THREAD

**Issue by steve-battisti** [fantasycalendar/kobold-plus-fight-club#37]
Hi! I love your KFC! I have noticed, though, that either your Native Environment filter does not work (on at least Chrome and Edge), or the monsters aren't appropriately tagged in the database with native environments.

**Steps to Reproduce**

1. Reset all filters
2. Select any source (or all sources)
3. Set Native Environment = Cave (or any environment)
4. I get 0 results every time, no matter which environment or source I choose.

Thank you!

**Comment by V13Axel** [comment]
Yep, looks like the filter was only matching on complete matches - So if you enabled all sources and selected "Cave," for example, it would only match two creatures, because those two creatures have `cave` as their only environment.

The above fix should go out for that soon, thanks for pointing this out!

**Comment by steve-battisti** [comment]
Awesome, thank you!

**Comment by steve-battisti** [comment]
Looks great, thank you!
