### ISSUE TITLE
Missing info when importing to improved initiatie

### ISSUE THREAD

**Issue by bootzin** [fantasycalendar/kobold-plus-fight-club#4]
Whenever I import an encounter to Improved Initiative, the name and health of the enemies is correct, but the sheet is otherwise completely blank.

**Comment by V13Axel** [comment]
This is a limitation of Improved Initiative, and not something we can really make happen at the moment.

In short: II requires the full stat block to be sent when the user is sent over, which would mean K+FC needs to have the entirety of the stat block(s) available to it.

Since we don't intend to publish WotC's copyrighted materials, this isn't something that can be done. We've been in talks with them a little bit about making the integration a bit tighter, so perhaps something may work for this in the future. 

That said, I wouldn't expect this any time soon.
